### ISSUE TITLE
Web.HttpContextAccessor更好的赋值方法？

### ISSUE THREAD

**Issue by Siloen** [bing-framework/Bing.Utils#1]
问下对Web中HttpContextAccessor进行赋值的最佳实践是什么样子的，属性注入？

**Comment by jianxuanbing** [comment]
可参照以下链接方式进行赋值。
[https://github.com/bing-framework/Bing.NetCore/blob/9892e0a30e16aa33341a0b24a0451f71d1216fd5/modules/admin/src/Bing.Admin/Modules/AppModule.cs#L82](https://github.com/bing-framework/Bing.NetCore/blob/9892e0a30e16aa33341a0b24a0451f71d1216fd5/modules/admin/src/Bing.Admin/Modules/AppModule.cs#L82)
